Improve the documentation regarding contributions
Alamofire/Alamofire pull request #3500
Opened 2021-09-27 20:21 UTC by TiagoMaiaL

### Issue Link :link:

https://forums.swift.org/t/broken-unit-tests-for-the-ios-scheme/52371/5

### Goals :soccer:
- Document how to contribute to the project by sending pull requests. 
- Document how to configure the automated tests to be run.

### Implementation Details :construction:
I've changed the `CONTRIBUTING.md` file, adding a section about pull requests. I've also linked it from the project  `README.md`.

2021-10-03 01:11 UTC, jshier requested changes
Looks pretty good, just some phrasing suggestions. Thanks for this!

2021-10-03 01:11 UTC, jshier commented on CONTRIBUTING.md
> +You can contribute by fixing bugs or adding new features. For larger code changes, we first recommend them to be discussed in the [project issues](https://github.com/Alamofire/Alamofire/issues) or in
```suggestion
You can contribute by fixing bugs or adding new features. For larger code changes, we first recommend discussing them in our [GitHub issues](https://github.com/Alamofire/Alamofire/issues) or on our [Swift Forums](https://forums.swift.org/c/related-projects/alamofire/). When submitting a pull request, please add relevant tests and ensure your changes don't break any existing tests (see [Automated Tests](#automated-tests) below).
```

2021-10-03 01:11 UTC, jshier commented on CONTRIBUTING.md
> +The tests depend on [Firewalk](https://github.com/Alamofire/Firewalk), our HTTP test server. To run the automated tests, you first need to have the server running locally.
```suggestion
Alamofire's tests depend on our [Firewalk](https://github.com/Alamofire/Firewalk) test server. To run the automated tests, you first need to have the server running locally. 
```

2021-10-03 01:11 UTC, jshier commented on CONTRIBUTING.md
> +- To launch the server: `firewalk &`
```suggestion
- To run and detach the server: `firewalk &`
- To stop the server, run `kill` and provide the pid output after launch.
```

2021-10-03 01:11 UTC, jshier commented on README.md
> +Please read the instructions detailed in [CONTRIBUTING.md](./CONTRIBUTING.md).
```suggestion
Before contributing to Alamofire, please read the instructions detailed our [contribution guide](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).
```

2021-10-03 13:54 UTC, TiagoMaiaL commented
Thanks for the correction and Improvements. I just applied them.

2021-10-04 02:20 UTC, jshier approved these changes
Thanks!

2021-10-04 02:20 UTC, merged